const DEFAULT_BOSSES = [
    { id: 'b_bm_ex', name: 'Black Mage', kana: '暗黒の魔法使い', difficulty: 'EXTREME', meso: 18000000000, type: 'MONTHLY' },
    { id: 'b_kaling_ex', name: 'Kaling', kana: 'カリーン', difficulty: 'EXTREME', meso: 6026000000, type: 'WEEKLY' },
    { id: 'b_fa_ex', name: 'First Adversary', kana: '最初の対敵者', difficulty: 'EXTREME', meso: 5880000000, type: 'WEEKLY' },
    { id: 'b_kalos_ex', name: 'Kalos the Guardian', kana: '監視者カロス', difficulty: 'EXTREME', meso: 5200000000, type: 'WEEKLY' },
    { id: 'b_bm_hard', name: 'Black Mage', kana: '暗黒の魔法使い', difficulty: 'HARD', meso: 4500000000, type: 'MONTHLY' },
    { id: 'b_seren_ex', name: 'Chosen Seren', kana: '選ばれし者セレン', difficulty: 'EXTREME', meso: 4235000000, type: 'WEEKLY' },
    { id: 'b_baldrix_hard', name: 'Baldrix', kana: 'バルドリックス', difficulty: 'HARD', meso: 4200000000, type: 'WEEKLY' },
    { id: 'b_limbo_hard', name: 'Limbo', kana: 'リンボ', difficulty: 'HARD', meso: 3745000000, type: 'WEEKLY' },
    { id: 'b_kaling_hard', name: 'Kaling', kana: 'カリーン', difficulty: 'HARD', meso: 2990000000, type: 'WEEKLY' },
    { id: 'b_fa_hard', name: 'First Adversary', kana: '最初の対敵者', difficulty: 'HARD', meso: 2940000000, type: 'WEEKLY' },
    { id: 'b_baldrix_normal', name: 'Baldrix', kana: 'バルドリクス', difficulty: 'NORMAL', meso: 2800000000, type: 'WEEKLY' },
    { id: 'b_kalos_chaos', name: 'Kalos the Guardian', kana: '監視者カロス', difficulty: 'CHAOS', meso: 2600000000, type: 'WEEKLY' },
    { id: 'b_limbo_normal', name: 'Limbo', kana: 'リンボ', difficulty: 'NORMAL', meso: 2100000000, type: 'WEEKLY' },
    { id: 'b_kaling_normal', name: 'Kaling', kana: 'カリーン', difficulty: 'NORMAL', meso: 1506500000, type: 'WEEKLY' },
    { id: 'b_lotus_ex', name: 'Lotus', kana: 'スウ', difficulty: 'EXTREME', meso: 1397500000, type: 'WEEKLY' },
    { id: 'b_fa_normal', name: 'First Adversary', kana: '最初の対敵者', difficulty: 'NORMAL', meso: 1365000000, type: 'WEEKLY' },
    { id: 'b_kalos_normal', name: 'Kalos the Guardian', kana: '監視者カロス', difficulty: 'NORMAL', meso: 1300000000, type: 'WEEKLY' },
    { id: 'b_seren_hard', name: 'Chosen Seren', kana: '選ばれし者セレン', difficulty: 'HARD', meso: 1096562500, type: 'WEEKLY' },
    { id: 'b_kaling_easy', name: 'Kaling', kana: 'カリーン', difficulty: 'EASY', meso: 1031250000, type: 'WEEKLY' },
    { id: 'b_fa_easy', name: 'First Adversary', kana: '最初の対敵者', difficulty: 'EASY', meso: 985000000, type: 'WEEKLY' },
    { id: 'b_kalos_easy', name: 'Kalos the Guardian', kana: '監視者カロス', difficulty: 'EASY', meso: 937500000, type: 'WEEKLY' },
    { id: 'b_seren_normal', name: 'Chosen Seren', kana: '選ばれし者セレン', difficulty: 'NORMAL', meso: 889021875, type: 'WEEKLY' },
    { id: 'b_vhilla_hard', name: 'Verus Hilla', kana: '真・ヒルラ', difficulty: 'HARD', meso: 762105000, type: 'WEEKLY' },
    { id: 'b_darknell_hard', name: 'Darknell', kana: 'デュンケル', difficulty: 'HARD', meso: 667920000, type: 'WEEKLY' },
    { id: 'b_will_hard', name: 'Will', kana: 'ウィル', difficulty: 'HARD', meso: 621810000, type: 'WEEKLY' },
    { id: 'b_gas_chaos', name: 'Guardian Angel Slime', kana: 'Gスライム', difficulty: 'CHAOS', meso: 600578125, type: 'WEEKLY' },
    { id: 'b_vhilla_normal', name: 'Verus Hilla', kana: '真・ヒルラ', difficulty: 'NORMAL', meso: 581880000, type: 'WEEKLY' },
    { id: 'b_gloom_chaos', name: 'Gloom', kana: 'ダスク', difficulty: 'CHAOS', meso: 563945000, type: 'WEEKLY' },
    { id: 'b_lucid_hard', name: 'Lucid', kana: 'ルシード', difficulty: 'HARD', meso: 504000000, type: 'WEEKLY' },
    { id: 'b_lotus_hard', name: 'Lotus', kana: 'スウ', difficulty: 'HARD', meso: 444675000, type: 'WEEKLY' },
    { id: 'b_damien_hard', name: 'Damien', kana: 'デミアン', difficulty: 'HARD', meso: 421875000, type: 'WEEKLY' },
    { id: 'b_darknell_normal', name: 'Darknell', kana: 'デュンケル', difficulty: 'NORMAL', meso: 316875000, type: 'WEEKLY' },
    { id: 'b_gloom_normal', name: 'Gloom', kana: 'ダスク', difficulty: 'NORMAL', meso: 297675000, type: 'WEEKLY' },
    { id: 'b_will_normal', name: 'Will', kana: 'ウィル', difficulty: 'NORMAL', meso: 279075000, type: 'WEEKLY' },
    { id: 'b_lucid_normal', name: 'Lucid', kana: 'ルシード', difficulty: 'NORMAL', meso: 253828125, type: 'WEEKLY' },
    { id: 'b_will_easy', name: 'Will', kana: 'ウィル', difficulty: 'EASY', meso: 246744750, type: 'WEEKLY' },
    { id: 'b_lucid_easy', name: 'Lucid', kana: 'ルシード', difficulty: 'EASY', meso: 237009375, type: 'WEEKLY' },
    { id: 'b_gas_normal', name: 'Guardian Angel Slime', kana: 'Gスライム', difficulty: 'NORMAL', meso: 231673500, type: 'WEEKLY' },
    { id: 'b_damien_normal', name: 'Damien', kana: 'デミアン', difficulty: 'NORMAL', meso: 169000000, type: 'WEEKLY' },
    { id: 'b_lotus_normal', name: 'Lotus', kana: 'スウ', difficulty: 'NORMAL', meso: 162562500, type: 'WEEKLY' },
    { id: 'b_mitu_normal', name: 'Mitsuhide', kana: 'アケチミツヒデ', difficulty: 'NORMAL', meso: 144000000, type: 'WEEKLY' },
    { id: 'b_papa_chaos', name: 'Papulatus', kana: 'ビシャスプラント', difficulty: 'CHAOS', meso: 132250000, type: 'WEEKLY' },
    { id: 'b_vellum_chaos', name: 'Vellum', kana: 'ベルルム', difficulty: 'CHAOS', meso: 105062500, type: 'WEEKLY' },
    { id: 'b_mag_hard', name: 'Magnus', kana: 'マグナス', difficulty: 'HARD', meso: 95062500, type: 'WEEKLY' },
    { id: 'b_pno_normal', name: 'Princess No', kana: 'ノウ姫', difficulty: 'NORMAL', meso: 81000000, type: 'WEEKLY' },
    { id: 'b_zakum_chaos', name: 'Zakum', kana: 'ジャクム', difficulty: 'CHAOS', meso: 81000000, type: 'WEEKLY' },
    { id: 'b_pierre_chaos', name: 'Pierre', kana: 'ピエール', difficulty: 'CHAOS', meso: 81000000, type: 'WEEKLY' },
    { id: 'b_bon_chaos', name: 'Von Bon', kana: 'バンバン', difficulty: 'CHAOS', meso: 81000000, type: 'WEEKLY' },
    { id: 'b_queen_chaos', name: 'Crimson Queen', kana: 'ブラッディクイーン', difficulty: 'CHAOS', meso: 81000000, type: 'WEEKLY' },
    { id: 'b_cygnus_normal', name: 'Cygnus', kana: 'シグナス', difficulty: 'NORMAL', meso: 72250000, type: 'WEEKLY' },
    { id: 'b_pink_chaos', name: 'Pink Bean', kana: 'ピンクビーン', difficulty: 'CHAOS', meso: 64000000, type: 'WEEKLY' },
    { id: 'b_hilla_hard', name: 'Hilla', kana: 'ヒルラ', difficulty: 'HARD', meso: 56250000, type: 'WEEKLY' },
    { id: 'b_mag_normal', name: 'Magnus', kana: 'マグナス', difficulty: 'NORMAL', meso: 12960000, type: 'DAILY' },
    { id: 'b_ark_normal', name: 'Arkarium', kana: 'アーカイラム', difficulty: 'NORMAL', meso: 12602500, type: 'DAILY' },
    { id: 'b_pink_normal', name: 'Pink Bean', kana: 'ピンクビーン', difficulty: 'NORMAL', meso: 7022500, type: 'DAILY' },
    { id: 'b_gollux_normal', name: 'Gollux', kana: 'ヴェラッド', difficulty: 'NORMAL', meso: 0, type: 'DAILY' }
];

const DEFAULT_DAILIES = [
    { id: 'd_mp', name: 'Monster Park', kana: 'モンパ', type: 'MONPA' },
    { id: 'd_arc', name: 'Arcane Daily', kana: 'アーケインデイリー', type: 'SYMBOL' },
    { id: 'd_sac', name: 'Sacred Daily', kana: 'オーセンティックデイリー', type: 'SYMBOL' },
    { id: 'd_com', name: 'Commeric', kana: 'コメルツ', type: 'OTHER' }
];

const DEFAULT_WEEKLIES = [
    { id: 'w_mpe', name: 'Monster Park Ex', kana: 'モンパEX', type: 'MONPA' },
    { id: 'w_high', name: 'High mountain', kana: 'ハイマウンテン', type: 'EPIC_DUNGEON' },
    { id: 'w_ang', name: 'Angler Company', kana: 'アングラー', type: 'EPIC_DUNGEON' },
    { id: 'w_sym', name: 'Symbol weekly', kana: 'シンボル週', type: 'SYMBOL' },
    { id: 'w_erda', name: 'Erda\'s Request', kana: 'ソルエルダ', type: 'HEXA' },
    { id: 'w_cul', name: 'Culvert', kana: '水路', type: 'GUILD' }
];